### ISSUE TITLE
Finalize Video Content for Saturday Shoot

### ISSUE THREAD

**Issue by abbycabs** [MozillaFoundation/open-leadership-101#1]
For the two videos
1. Firefox story
2. Participation skills

- [x] finalize talking points for both videos - @zee-moz 
- [x] run final content by stakeholders (julia/lucy/christos), asyc - @acabunoc
- [x] last edits from feedback
- [x] run by lotta/kevin to capture Mark's voice - @zee-moz
- [x] put talking points in slides as a makeshift teleprompter - @zee-moz 
- [x] instructions for Mark & Abby (what should we wear?) - @natalieworth ?
- [x] By Friday Feb 24: send Mark + Phia his talking points plus instructions - @acabunoc

**Comment by abbycabs** [comment]
Hey @zee-moz, do you think the content is ready to by the group one last time?

**Comment by natalieworth** [comment]
Hey Abby,
For clothing, I'd suggest something solid (no patterns or anything) and avoid black, grey, and white if the background is going to be light. I think Chun could hopefully provide some expertise too. I'm sure he has a good idea of what could look best too! I personally prefer more casual attire too when watching interview or tech focused videos vs. a formal wear, but I guess it would also depend on the tone of the video and how professional or approachable we want to make it?

**Comment by abbycabs** [comment]
Thanks @natalieworth! I believe we decided on a black background (not light) -- I'll run this by Chun to see if he has anything else to add :)

**Comment by abbycabs** [comment]
From Chun: "Casual attire (like a relaxed collared shirt nothing too dressy) would be great :) "

Final dress code: 
* Casual attire (like a relaxed collared shirt nothing too dressy)
* Solid colours (no patterns or large logos)
* No black, grey or white

**Comment by zee-moz** [comment]
hey there, I revised Mark's video and @acabunoc  and I did updated talking points for her video. Most recent versions in the [OLTs Jr working doc.](https://docs.google.com/document/d/1OuBI2L-8gszdQ3dtFCGn6xvKb8veC-LC2shpr04rFJ0/edit?usp=sharing). ready for final comments and tweaks! 😸

**Comment by abbycabs** [comment]
Flagging @lucyeoh, @bacharakis & @jvallera 
We'd love your 👀 on the final version of the two videos we're shooting this Saturday! I'll be sending these talking points to Mark tomorrow morning.

[Firefox story](https://docs.google.com/document/d/1OuBI2L-8gszdQ3dtFCGn6xvKb8veC-LC2shpr04rFJ0/edit#heading=h.zgsd7ac1uyh0)

[Participation skills](https://docs.google.com/document/d/1OuBI2L-8gszdQ3dtFCGn6xvKb8veC-LC2shpr04rFJ0/edit#heading=h.uqyw3y35wkc)

**Comment by bacharakis** [comment]
Thanks! I left some comments in the documents but in general they are look more than good ;)

**Comment by abbycabs** [comment]
Sent final instructions to Mark & Phia with a link to the google doc!

**Comment by zee-moz** [comment]
@acabunoc I reviewed all the comments, incorporated all the feedback, and have one teeny remaining question for you on Mark's video-- otherwise we're good to go!

**Comment by abbycabs** [comment]
updated first comment to add running this by communications to capture mark's voice and putting it all in slides. Thanks @zee-moz!

**Comment by zee-moz** [comment]
@acabunoc I went ahead and put the talking points in slides, and sent those to Kevin & Lotta, just in case we don't hear back from them in time for me to do that this afternoon. 
They can make edits/comments there, I'm OK with that.

**Comment by abbycabs** [comment]
shoot done! Closing 💯
